name: CI

on:
  push:
      branches: [ "master" ]
  pull_request:
      branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Arcus C Client Dependency Packages
      run: sudo apt-get install -qq build-essential libtool pandora-build
    - name: Cache Arcus Server Directory
      id: arcus-cache
      uses: actions/cache@v3.3.2
      with:
        path: ~/arcus
        key: ${{runner.os}}-arcus
    - name: Install Arcus Server
      if: steps.arcus-cache.outputs.cache-hit != 'true'
      run: |
           git clone https://github.com/naver/arcus-memcached
           cd arcus-memcached
           ./deps/install.sh $HOME/arcus
           ./config/autorun.sh
           ./configure --prefix=$HOME/arcus
           make && make install
    - name: Build Arcus C Client
      run: |
           ./config/autorun.sh
           ./configure --with-memcached=$HOME/arcus/bin/memcached \
                       --with-memcached_engine=$HOME/arcus/lib/default_engine.so
           make
    - name: Test ARCUS C Client
      run: make test
